### ISSUE TITLE
NPE when entity factory implementing class is declared private

### ISSUE THREAD

**Issue by AlmasB** [AlmasB/FXGL#673] opened 2019-10-05 16:53 UTC
1. Find the code that throws NPE when an entity factory class is declared private
2. Either fix NPE (so private factories are allowed) or throw a meaningful exception stating that private factories are not allowed. The former is preferred.

**Comment by SNException** [comment] 2019-10-05 18:42
Hi.
I tried to reproduce this error. However instead of a NullPointerException I am actually getting a IllegalAccessException.
```
java.lang.IllegalAccessException: class com.almasb.fxgl.core.reflect.ReflectionUtils (in module com.almasb.fxgl.core) cannot access a member of class tutorial.BreakoutApp$BreakoutFactory (in module samples.main) with modifiers "public"
	at java.base/jdk.internal.reflect.Reflection.newIllegalAccessException(Reflection.java:361)
	at java.base/java.lang.reflect.AccessibleObject.checkAccess(AccessibleObject.java:591)
	at java.base/java.lang.reflect.Method.invoke(Method.java:558)
	at com.almasb.fxgl.core/com.almasb.fxgl.core.reflect.ReflectionUtils.lambda$findMethodsMapToFunctions$1(ReflectionUtils.java:87)
	at com.sun.proxy.$Proxy3.apply(Unknown Source)
	at com.almasb.fxgl.entity/com.almasb.fxgl.entity.GameWorld$create$2.invoke(GameWorld.kt:398)
	at com.almasb.fxgl.entity/com.almasb.fxgl.entity.GameWorld$create$2.invoke(GameWorld.kt:33)
	at com.almasb.fxgl.core/com.almasb.fxgl.core.util.DSLKt.tryCatchRoot(DSL.kt:33)
	at com.almasb.fxgl.entity/com.almasb.fxgl.entity.GameWorld.create(GameWorld.kt:398)
	at com.almasb.fxgl.entity/com.almasb.fxgl.entity.GameWorld.spawn(GameWorld.kt:371)
	at com.almasb.fxgl.entity/com.almasb.fxgl.entity.GameWorld.spawn(GameWorld.kt:359)
	at com.almasb.fxgl.all/com.almasb.fxgl.dsl.FXGL$Companion.spawn(FXGL.kt:309)
	at com.almasb.fxgl.all/com.almasb.fxgl.dsl.FXGL.spawn(FXGL.kt)
	at samples.main/tutorial.BreakoutApp.initGame(BreakoutApp.java:82)
	at com.almasb.fxgl.all/com.almasb.fxgl.app.LoadingScene$InitAppTask.initGame(LoadingScene.kt:137)
	at com.almasb.fxgl.all/com.almasb.fxgl.app.LoadingScene$InitAppTask.call(LoadingScene.kt:106)
	at com.almasb.fxgl.all/com.almasb.fxgl.app.LoadingScene$InitAppTask.call(LoadingScene.kt:94)
	at javafx.graphics/javafx.concurrent.Task$TaskCallable.call(Task.java:1425)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
```
I tested this by setting some of the EntityFactory classes inside the tutorial package to private.
In the case of the above stacktrace it was the `BreakoutFactory` of the `BreakoutApp`.

If that is the error you are describing then this could be fixed by modifying the `ReflectionUtils` class by adding the following call to the `findMethodsMapToFunctions` method:

 ```java
   public static <T, R, F extends Function<T, R>, A extends Annotation> Map<A, F>
        findMethodsMapToFunctions(Object instance, Class<A> annotationClass, Class<F> functionClass) {

        Map<A, F> map = new HashMap<>();

        findMethods(instance, annotationClass).forEach((annotation, method) -> {
                // we create an instance implementing F on the fly
                // so that high-level calling code stays clean

                // ------------------------------------------------------------------
                method.setAccessible(true); // <------ This call solves it for me
                // ------------------------------------------------------------------

                F function = (F) Proxy.newProxyInstance(functionClass.getClassLoader(),
                        new Class[] { functionClass },
                        (proxy, proxyMethod, args) -> method.invoke(instance, args));

                map.put(annotation, function);
            }
        );

        return map;
    }
```
What do you think? Or perhaps you are talking about a different issue?

**Comment by AlmasB** [comment] 2019-10-05 18:48
Interesting, I think you've just found a similar issue, but not the one I found. Though I suspect both are fixed using similar (or maybe same) approaches. In [this sample](https://github.com/AlmasB/FXGL/blob/dev/fxgl-samples/src/main/java/sandbox/BenchmarkSample.java) if the factory class is set to private, then NPE is thrown. Wonder if it's related to the class being `private static` and inside a different class vs `private` but top-level. Please can you check this sample and see if your fix solves it too?

**Comment by SNException** [comment] 2019-10-06 07:47
Hmm. I think I am still doing something different from you. I tested this now with the `BenchmarkSample` and in this case I also get `IllegalAccessException` when I am setting the Factory class to private (I also tried it with and without static).

So it now looks like this:
```java
    private class BenchmarkFactory implements EntityFactory {

        @Preload(10000)
        @Spawns("e")
        public Entity newEntity(SpawnData data) {
            return new Entity();
        }
    }
```
But still produces IllegalAccessException instead of NPE:
```
java.security.PrivilegedActionException: java.lang.IllegalAccessException: class com.almasb.fxgl.core.reflect.ReflectionUtils (in module com.almasb.fxgl.core) cannot access a member of class sandbox.BenchmarkSample$BenchmarkFactory (in module samples.main) with modifiers "public"
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at javafx.graphics/com.sun.javafx.tk.quantum.GlassViewEventHandler.lambda$handleKeyEvent$1(GlassViewEventHandler.java:248)
	at javafx.graphics/com.sun.javafx.tk.quantum.QuantumToolkit.runWithoutRenderLock(QuantumToolkit.java:411)
	at javafx.graphics/com.sun.javafx.tk.quantum.GlassViewEventHandler.handleKeyEvent(GlassViewEventHandler.java:247)
	at javafx.graphics/com.sun.glass.ui.View.handleKeyEvent(View.java:547)
	at javafx.graphics/com.sun.glass.ui.View.notifyKey(View.java:971)
	at javafx.graphics/com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
	at javafx.graphics/com.sun.glass.ui.win.WinApplication.lambda$runLoop$3(WinApplication.java:174)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.lang.IllegalAccessException: class com.almasb.fxgl.core.reflect.ReflectionUtils (in module com.almasb.fxgl.core) cannot access a member of class sandbox.BenchmarkSample$BenchmarkFactory (in module samples.main) with modifiers "public"
	at java.base/jdk.internal.reflect.Reflection.newIllegalAccessException(Reflection.java:361)
	at java.base/java.lang.reflect.AccessibleObject.checkAccess(AccessibleObject.java:591)
	at java.base/java.lang.reflect.Method.invoke(Method.java:558)
	at com.almasb.fxgl.core/com.almasb.fxgl.core.reflect.ReflectionUtils.lambda$findMethodsMapToFunctions$1(ReflectionUtils.java:86)
	at com.sun.proxy.$Proxy4.apply(Unknown Source)
	at com.almasb.fxgl.entity/com.almasb.fxgl.entity.GameWorld$create$2.invoke(GameWorld.kt:396)
	at com.almasb.fxgl.entity/com.almasb.fxgl.entity.GameWorld$create$2.invoke(GameWorld.kt:33)
	at com.almasb.fxgl.core/com.almasb.fxgl.core.util.DSLKt.tryCatchRoot(DSL.kt:33)
	at com.almasb.fxgl.entity/com.almasb.fxgl.entity.GameWorld.create(GameWorld.kt:396)
	at samples.main/sandbox.BenchmarkSample.spawn(BenchmarkSample.java:45)
	at samples.main/sandbox.BenchmarkSample.lambda$initInput$0(BenchmarkSample.java:32)
	at com.almasb.fxgl.all/com.almasb.fxgl.dsl.FXGL$Companion$onKeyDown$1.onActionBegin(FXGL.kt:256)
	at com.almasb.fxgl.input/com.almasb.fxgl.input.UserAction.begin$fxgl_input(UserAction.kt:37)
	at com.almasb.fxgl.input/com.almasb.fxgl.input.Input.handlePressed(Input.kt:195)
	at com.almasb.fxgl.input/com.almasb.fxgl.input.Input.onKeyEvent(Input.kt:156)
	at com.almasb.fxgl.all/com.almasb.fxgl.app.MainWindow$1$1.invoke(MainWindow.kt:82)
	at com.almasb.fxgl.all/com.almasb.fxgl.app.MainWindow$1$1.invoke(MainWindow.kt:35)
	at com.almasb.fxgl.core/com.almasb.fxgl.core.fsm.StateMachine.runOnActiveStates(StateMachine.kt:60)
	at com.almasb.fxgl.all/com.almasb.fxgl.app.MainWindow$1.invoke(MainWindow.kt:82)
	at com.almasb.fxgl.all/com.almasb.fxgl.app.MainWindow$1.invoke(MainWindow.kt:35)
	at com.almasb.fxgl.all/com.almasb.fxgl.app.MainWindow$sam$javafx_event_EventHandler$0.handle(MainWindow.kt)
	at javafx.base/com.sun.javafx.event.CompositeEventHandler$NormalEventHandlerRecord.handleBubblingEvent(CompositeEventHandler.java:218)
	at javafx.base/com.sun.javafx.event.CompositeEventHandler.dispatchBubblingEvent(CompositeEventHandler.java:80)
	at javafx.base/com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:238)
	at javafx.base/com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:191)
	at javafx.base/com.sun.javafx.event.CompositeEventDispatcher.dispatchBubblingEvent(CompositeEventDispatcher.java:59)
	at javafx.base/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:58)
	at javafx.base/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at javafx.base/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at javafx.base/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at javafx.base/com.sun.javafx.event.EventUtil.fireEventImpl(EventUtil.java:74)
	at javafx.base/com.sun.javafx.event.EventUtil.fireEvent(EventUtil.java:54)
	at javafx.base/javafx.event.Event.fireEvent(Event.java:198)
	at javafx.graphics/javafx.scene.Scene$KeyHandler.process(Scene.java:4070)
	at javafx.graphics/javafx.scene.Scene.processKeyEvent(Scene.java:2121)
	at javafx.graphics/javafx.scene.Scene$ScenePeerListener.keyEvent(Scene.java:2597)
	at javafx.graphics/com.sun.javafx.tk.quantum.GlassViewEventHandler$KeyEventNotification.run(GlassViewEventHandler.java:217)
	at javafx.graphics/com.sun.javafx.tk.quantum.GlassViewEventHandler$KeyEventNotification.run(GlassViewEventHandler.java:149)
	... 9 more

```
This is is solved by same method as described in my first comment.
I am on the latest commit of the `dev` branch (5e59400fba0cb6f829c877a8d0739eaa875adbb2).

**Comment by AlmasB** [comment] 2019-10-06 07:58
You are right, it *is* caused by IAE. My bad, I didn't read further than the error reporter text and seeing `null`, just assumed it was NPE

```
Message:  null
Type:  PrivilegedActionException
Method:  AccessController.doPrivileged()
Line:  Native Method
```

Please can you submit a PR with the fix. I don't think the fix changes the semantics of the `findMethodsMapToFunctions` method, so tests should still pass.

**Closed** 2019-10-06 09:03 UTC
Labels: help wanted, medium, type:enhancement
