### ISSUE TITLE
Remote Server Multi-player / Multi-team feature request.

### ISSUE THREAD

**Issue by smabitsela** [AlmasB/FXGL#1007] opened 2021-04-16 10:55 UTC
**Please discuss the feature ideas on [Gitter](https://gitter.im/AlmasB/FXGL) first. Then please describe the feature**
To be able to implement Input & Entity Replication on a setup consisting of a remote server hosting multiple FXGL clients in teams.

**Describe alternatives you've considered (optional)**

**Additional context (optional)**
At our training institute "https://www.wethinkcode.co.za/" we are required to create a multi-team (two teams, four players each) strategy game hosted on a remote server with eight clients connected. Each client choosing a team. Our request is to have the MultiplayerService be able to implement and Replicated such a setup on the screens of each player.

**Comment by AlmasB** [comment] 2021-05-23 18:00
Closed as duplicate of #883 
All updates to multiplayer service development will be tracked in #883

**Closed as completed by AlmasB** 2021-05-23 18:00 UTC
Labels: type:new feature
