### ISSUE TITLE
Parsing .tmx: add support for tilesets that use a collection of images

### ISSUE THREAD

**Issue by JosephChotard** [AlmasB/FXGL#752] opened 2020-02-14 13:59 UTC
When trying to load a map which contains tiles that are not in a tilesheet but in a collection of images, the game crashs as it divides by 0:
```
java.lang.ArithmeticException: / by zero
   at com.almasb.fxgl.entity.level.tiled.TilesetLoader.loadView(TilesetLoader.kt:84)
   at com.almasb.fxgl.entity.level.tiled.TMXLevelLoader.createTileLayerEntities(TMXLevelLoader.kt:79)
   at com.almasb.fxgl.entity.level.tiled.TMXLevelLoader.load(TMXLevelLoader.kt:50)
   at com.almasb.fxgl.app.services.AssetLoaderService.loadLevel(AssetLoaderService.kt:259)
   at com.almasb.fxgl.dsl.FXGL$Companion.setLevelFromMap(FXGL.kt:496)
   at com.almasb.fxgl.dsl.FXGL.setLevelFromMap(FXGL.kt)
```

**Comment by AlmasB** [comment] 2020-02-14 19:40
Please can you provide a minimal example that reproduces the above with the appropriate tmx and images for testing

**Comment by SergeMerzliakov** [comment] 2020-02-21 11:10
I have the same issue. Simple project attached.
[dungeon1.zip](https://github.com/AlmasB/FXGL/files/4235730/dungeon1.zip)

**Comment by AlmasB** [comment] 2020-02-22 09:05
@SergeMerzliakov thanks for the simple example. The example should now work. Since the `png` file is in the same dir as the `tmx` file, I updated the `.tmx` file to refer to 

`<image width="48" height="48" source="dirt.png"/>`, instead of

`<image width="48" height="48" source="../textures/dirt.png"/>`.

To get the latest build, you can use this:
```
<dependencies>
    <dependency>
        <groupId>com.github.almasb</groupId>
        <artifactId>fxgl</artifactId>
        <version>dev-SNAPSHOT</version>
    </dependency>
</dependencies>

<repositories>
    <repository>
        <id>oss.sonatype.org-snapshot</id>
        <url>http://oss.sonatype.org/content/repositories/snapshots</url>
    </repository>
</repositories>
```

Please let me know if this fixes the issue.

**Comment by AlmasB** [comment] 2020-02-22 09:06
@JosephChotard see if the new build works for you too

**Comment by AlmasB** [comment] 2020-03-10 11:52
@SergeMerzliakov @JosephChotard please can you check that this works. This should be fixed in version 11.8

**Comment by JosephChotard** [comment] 2020-03-21 14:45
No does not work: when trying to load a tileset, it's running the code as if it's a collection of images which means it does not work

**Comment by AlmasB** [comment] 2020-03-29 08:09
Please can you provide the problematic .tmx (with images) and a minimal example to reproduce the issue.

**Comment by AlmasB** [comment] 2020-12-02 19:22
This has been fixed and now [has a unit test](https://github.com/AlmasB/FXGL/blob/dev/fxgl-entity/src/test/kotlin/com/almasb/fxgl/entity/level/tiled/TMXLevelLoaderTest.kt#L105) associated with it.

**Closed by AlmasB** 2020-12-02 19:22 UTC
Labels: in progress, type:new feature
