### ISSUE TITLE
Pause main loop when the stage is minimized

### ISSUE THREAD

**Issue by SNException** [AlmasB/FXGL#428] opened 2017-11-14 19:47 UTC
Hi,

I just noticed something strange while playing around with FXGL and the newest space invader game. 
When the stage is minimized my CPU Usage went up by quiet a bit.
I've done some research in the library and found that if the stage is minimized the AnimationTimer (mainLoop) in the GameApplication class executes much faster than it should. Normally it should cap at 60 FPS but it went way faster. Can you confirm this? Or am I crazy? 😆 
I am not sure if thats maybe even a bug in the AnimationTimer class itself since I tried writing a small test without FXGL and I got the same result. Maybe that behavior is even expected and I just don't know.
But that would mean that if a game is running and gets minimized the whole game would update too fast.

Therefore my proposal would be in case that is something we want to resolve is that the game gets paused when minimized. I suppose we can add a changelistener to the focusproperty of the stage
and stop the mainloop accordingly.

The way I tested it was by incrementing a counter in the mainLoop and printing it. As soon as I
minimized the stage the counter incremented a lot faster.

**Comment by AlmasB** [comment] 2017-11-14 19:50
This is a very interesting behaviour and I suspect that JavaFX may have a key role in that. Yes it would be good to know when the stage is minimized (should be easy I think) and pause the main loop.

**Comment by AlmasB** [comment] 2017-11-14 20:03
To solve this ...

1. Add listener for minimize / restore stage events.
2. Fire menu key event for (`FXGL.getSettings().getMenuKey()`) on play state's input.

Depending on menus are enabled or not, the event will (_should_) be handled by existing code to open a game menu / pause menu.

**Comment by AlmasB** [comment] 2017-11-14 20:05
Actually, did you say that CPU usage went up? So it's the `mainLoop` we want to pause and not the game?

**Comment by SNException** [comment] 2017-11-14 20:12
Yes, since the main loop was executing a lot faster the cpu usage went up.
Therefore we should pause the mainLoop, yes.

**Comment by AlmasB** [comment] 2017-11-14 20:16
Have reproduced this in `mainLoop`. Created a pure JavaFX app with `AnimationTimer` and just a single `Pane`, no such issue. Wonder what FXGL does that messes with CPU...

**Comment by SNException** [comment] 2017-11-14 20:18
Hmm, did the AnimationTimer in your test execute faster when minimized? I suppose since it is just an emtpy pane it would not have much effect on the cpu. Not sure though.

**Comment by AlmasB** [comment] 2017-11-14 20:23
You are correct, I've just run within FXGL, but set the scene with `Pane` only. No issues, so potentially a bug somewhere, either FXGL or JavaFX. I think your idea should work, listen for minimized events (not necessarily focus events) and `mainLoop.stop()`, then resume. I'll see if it's easy fix, since I'm looking at it right now anyway.

**Comment by SNException** [comment] 2017-11-14 20:31
Sounds great. 👍

**Comment by AlmasB** [comment] 2017-11-14 20:44
@SNException could you check that the issue is fixed? If yes, we can close the issue

**Comment by mokun** [comment] 2017-11-15 00:20
I observed this bug as well on my app and I was going to report it...

Since I use maven, do you by any chance have 0.4.0-snapshot in maven that I can test it ?

**Comment by AlmasB** [comment] 2017-11-15 11:40
Currently away, will deploy `0.4.0-SNAPSHOT` today. You will need to add:

```
    <repositories>
        <repository>
            <id>oss.sonatype.org-snapshot</id>
            <url>http://oss.sonatype.org/content/repositories/snapshots</url>
        </repository>
    </repositories>
```

**Comment by SNException** [comment] 2017-11-15 15:25
@AlmasB Just tested it and your fix works perfectly 👍

**Comment by AlmasB** [comment] 2017-11-15 16:52
@mokun I've just pushed `0.4.0-SNAPSHOT` for you to test, make sure to include the snapshot repo in `pom.xml`, seen above.

**Comment by mokun** [comment] 2017-11-15 21:13
I just tested it. With 0.4.0-SNAPSHOT, there is no more spurious increase of CPU when the app is minimized. 

Also, unexpectedly, the normal CPU util went down by ~20% on average. I suppose many optimizations have been done since 0.3.9 and that's great news !

**Comment by AlmasB** [comment] 2017-11-16 14:22
Yes, a very good suggestion. While we can keep the fix for now, your suggestion is how it should be solved in the long term

**Closed** 2017-11-21 20:20 UTC
Labels: help wanted, type:new feature
